// Package image provides image storage and anti-hotlinking access capabilities.
//
// Design principles:
//   - Only business-domain URLs are exposed; the underlying storage provider
//     is never revealed to callers or end users.
//   - Images are stored with private ACL. Accessing an image requires a signed, time-limited
//     business token generated by this package.
//   - Access tokens optionally bind a viewer ID to prevent URL sharing as a hotlink host.
//     Tokens carry an expiry so leaked URLs become invalid automatically.
//
// Typical flow:
//
//  1. Initialize the service:
//
//     objstore.Init(&objstore.Config{...})
//     svc, err := image.NewService(image.Config{
//         Bucket:          "my-bucket",
//         SignSecret:      "random-32-byte-secret",
//         DefaultTokenTTL: 30 * time.Minute,
//     }, myMetaStore)
//
//  2. Upload an image (in your upload HTTP handler):
//
//     img, err := svc.Upload(ctx, &image.UploadRequest{
//         Body:     file,
//         MimeType: "image/jpeg",
//         OwnerID:  userID,
//         MaxBytes: 5 << 20, // 5 MiB
//     })
//     // persist img.ID in your database
//
//  3. Build an access URL (when constructing API responses):
//
//     token, err := svc.BuildAccessToken(img.ID, viewerID)
//     accessURL := "https://api.example.com/image/v?t=" + token
//
//  4. Serve the image (in your view HTTP handler):
//
//     presignedURL, err := svc.ResolveAccessToken(ctx, token, viewerID)
//     // err != nil → respond 403
//     // err == nil → http.Redirect(w, r, presignedURL, http.StatusFound)
package image

import (
	"context"
	"io"
	"time"
)

// Image represents image metadata from the business layer's perspective.
// It deliberately excludes object-storage details (bucket, key, endpoint).
type Image struct {
	ID        string
	MimeType  string
	Size      int64     // bytes; 0 if unknown at upload time
	OwnerID   string    // uploader's user ID; empty for system uploads
	CreatedAt time.Time
}

// UploadRequest carries all parameters needed to store a new image.
type UploadRequest struct {
	Body     io.Reader // caller is responsible for closing
	MimeType string    // e.g. "image/jpeg"; auto-detected from content if empty
	Size     int64     // content length in bytes; 0 if unknown
	OwnerID  string    // optional uploader ID stored in metadata
	MaxBytes int64     // reject uploads that exceed this byte count; 0 means unlimited
}

// MetaStorage persists image metadata. Implemented by the application layer
// (typically a GORM model or sqlx query). Passing nil to NewService disables
// metadata persistence (useful for tests or ephemeral uploads).
type MetaStorage interface {
	Save(ctx context.Context, img *Image) error
	Get(ctx context.Context, id string) (*Image, error)
	Delete(ctx context.Context, id string) error
}
